import { User } from "../../src/types";

export const ResponsiveColsMap: Record<keyof User, string> = {
  _id: "hidden",
  id: "hidden",
  name: "",
  firstName: "hidden",
  lastName: "hidden",
  username: "hidden 2xl:table-cell",
  email: "hidden 2xl:table-cell",
  gender: "hidden 2xl:table-cell",
  characteristic: "hidden 2xl:table-cell",
  department: "hidden lg:table-cell",
  dob: "hidden 2xl:table-cell",
  avatar: "hidden",
  address: "hidden 2xl:table-cell",
  city: "hidden xl:table-cell",
  country: "hidden xl:table-cell",
  experience: "hidden",
  phone: "hidden",
  employed: "hidden",
  inProgress: "hidden md:table-cell",
  average: "hidden md:table-cell",
  ipAddress: "hidden 2xl:table-cell",
  medals: "hidden 2xl:table-cell",
  responseRateDynamic: "hidden",
  customerServiceDynamic: "hidden",
  customerServiceWithDynamic: "w-32",
  responseRateWithDynamic: "w-32",
  customerService: "hidden",
  responseRate: "hidden",
};

export const SearchColumns = [
  "_id",
  "firstName",
  "lastName",
  "username",
  "email",
  "department",
  "country",
  "city",
  "department",
  "gender",
];
